$(".contenttop:first").click(function(){
    $("#contentblock1").slideToggle();
  });
    $(".contenttop:eq(1)").click(function(){
    $("#contentblock2").slideToggle();
  });
    $(".contenttop:eq(2)").click(function(){
    $("#contentblock3").slideToggle();
  });